// This file is @generated by prost-build.
/// Command::Error
#[derive(serde::Deserialize, serde::Serialize, Clone, PartialEq, ::prost::Message)]
pub struct ExecuteError {
    #[prost(
        oneof = "execute_error::Error",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27"
    )]
    pub error: ::core::option::Option<execute_error::Error>,
}
/// Nested message and enum types in `ExecuteError`.
pub mod execute_error {
    #[derive(serde::Deserialize, serde::Serialize, Clone, PartialEq, ::prost::Oneof)]
    pub enum Error {
        #[prost(message, tag = "1")]
        KeyNotFound(()),
        #[prost(message, tag = "2")]
        RevisionTooLarge(super::Revisions),
        #[prost(message, tag = "3")]
        RevisionCompacted(super::Revisions),
        #[prost(int64, tag = "4")]
        LeaseNotFound(i64),
        #[prost(int64, tag = "5")]
        LeaseExpired(i64),
        #[prost(int64, tag = "6")]
        LeaseTtlTooLarge(i64),
        #[prost(int64, tag = "7")]
        LeaseAlreadyExists(i64),
        #[prost(message, tag = "8")]
        AuthNotEnabled(()),
        #[prost(message, tag = "9")]
        AuthFailed(()),
        #[prost(string, tag = "10")]
        UserNotFound(::prost::alloc::string::String),
        #[prost(string, tag = "11")]
        UserAlreadyExists(::prost::alloc::string::String),
        #[prost(message, tag = "12")]
        UserAlreadyHasRole(super::UserRole),
        #[prost(message, tag = "13")]
        NoPasswordUser(()),
        #[prost(string, tag = "14")]
        RoleNotFound(::prost::alloc::string::String),
        #[prost(string, tag = "15")]
        RoleAlreadyExists(::prost::alloc::string::String),
        #[prost(string, tag = "16")]
        RoleNotGranted(::prost::alloc::string::String),
        #[prost(message, tag = "17")]
        RootRoleNotExist(()),
        #[prost(message, tag = "18")]
        PermissionNotGranted(()),
        #[prost(message, tag = "19")]
        PermissionNotGiven(()),
        #[prost(message, tag = "20")]
        InvalidAuthManagement(()),
        #[prost(message, tag = "21")]
        InvalidAuthToken(()),
        #[prost(message, tag = "22")]
        TokenManagerNotInit(()),
        #[prost(message, tag = "23")]
        TokenNotProvided(()),
        #[prost(message, tag = "24")]
        TokenOldRevision(super::Revisions),
        #[prost(string, tag = "25")]
        DbError(::prost::alloc::string::String),
        #[prost(message, tag = "26")]
        PermissionDenied(()),
        #[prost(message, tag = "27")]
        Nospace(()),
    }
}
#[derive(serde::Deserialize, serde::Serialize, Clone, Copy, PartialEq, ::prost::Message)]
pub struct Revisions {
    #[prost(int64, tag = "1")]
    pub required_revision: i64,
    #[prost(int64, tag = "2")]
    pub current_revision: i64,
}
#[derive(serde::Deserialize, serde::Serialize, Clone, PartialEq, ::prost::Message)]
pub struct UserRole {
    #[prost(string, tag = "1")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
}
