// This file is @generated by prost-build.
#[derive(serde::Deserialize, serde::Serialize, Clone, Copy, PartialEq, ::prost::Message)]
pub struct Lease {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub ttl: i64,
    #[prost(int64, tag = "3")]
    pub remaining_ttl: i64,
}
#[derive(serde::Deserialize, serde::Serialize, Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaseInternalRequest {
    #[prost(message, optional, tag = "1")]
    pub lease_time_to_live_request:
        ::core::option::Option<super::etcdserverpb::LeaseTimeToLiveRequest>,
}
#[derive(serde::Deserialize, serde::Serialize, Clone, PartialEq, ::prost::Message)]
pub struct LeaseInternalResponse {
    #[prost(message, optional, tag = "1")]
    pub lease_time_to_live_response:
        ::core::option::Option<super::etcdserverpb::LeaseTimeToLiveResponse>,
}
