# @generated by `cargo buckal`

load("@prelude//rust:cargo_package.bzl", "cargo")
load("@buckal//:cargo_buildscript.bzl", __buildscript_run__="buildscript_run")

def _set_profile_flag(**kwargs):
    rustc_flags = kwargs.get("rustc_flags", []) + select({
        "buckal//config/mode:debug": ["-Copt-level=0"],
        "buckal//config/mode:release": ["-Copt-level=3"],
        "DEFAULT": [],
    })
    return rustc_flags

def _patch_buildscript_env(**kwargs):
    env = kwargs.get("env", {})
    env.update(OPT_LEVEL=select({
        "buckal//config/mode:debug": "0",
        "buckal//config/mode:release": "3",
        "DEFAULT": "0",
    }))
    env.update(DEBUG=select({
        "buckal//config/mode:debug": "1",
        "buckal//config/mode:release": "0",
        "DEFAULT": "1",
    }))
    return env

def rust_binary(name, **kwargs):
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_binary(name = name, **kwargs)

def rust_library(name, **kwargs):
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_library(name = name, **kwargs)

def buildscript_run(name, **kwargs):
    # Patch build script environment
    env = kwargs.get("env", {})
    env = _patch_buildscript_env(env=env)
    kwargs.update(env=env)
    __buildscript_run__(name = name, **kwargs)