# @generated by `cargo buckal`

load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

def system_demo_rust_toolchain():
    # Buck prelude only maps a small set of CPU constraints to Rust triples by
    # default. We provide an explicit mapping so `--target-platforms` works.
    system_rust_toolchain(
        name = "rust",
        rustc_target_triple = select({
            "prelude//os/constraints:linux": "x86_64-unknown-linux-gnu",
            "prelude//os/constraints:macos": "aarch64-apple-darwin",
            "prelude//os/constraints:windows": "x86_64-pc-windows-msvc",
            "DEFAULT": "x86_64-unknown-linux-gnu",
        }),
        default_edition = "2021",
        visibility = ["PUBLIC"],
    )
