// This file is @generated by prost-build.
/// For compatibility of gRPC implementations that do not support the `optional`
/// keyword
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OptionalU64 {
    #[prost(uint64, tag = "1")]
    pub value: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProposeId {
    #[prost(uint64, tag = "1")]
    pub client_id: u64,
    #[prost(uint64, tag = "2")]
    pub seq_num: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Member {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub peer_urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub client_urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "5")]
    pub is_learner: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CmdResult {
    #[prost(oneof = "cmd_result::Result", tags = "1, 2")]
    pub result: ::core::option::Option<cmd_result::Result>,
}
/// Nested message and enum types in `CmdResult`.
pub mod cmd_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// The serialized command execute result
        /// The original type is Command::ER
        #[prost(bytes, tag = "1")]
        Ok(::prost::alloc::vec::Vec<u8>),
        /// The serialized command error
        /// The original type is Command::Error
        #[prost(bytes, tag = "2")]
        Error(::prost::alloc::vec::Vec<u8>),
    }
}
/// All possible errors that the curp server may encounter.
/// This error will be serialized in the `detail` of the gRPC Status and returned
/// to clients. The reason for not dividing into some levels is for the
/// convenience of the client to make judgments. If some errors never be checked
/// in client, they could be merged into `Internal`.
///
/// Feel free to use `google.protobuf.Empty` as the client never concerned the
/// details happens in the server. If your error needs the context to be passed
/// within the server, you can implement a separate error and implement the
/// From<YourError> trait for `CurpError`, see `StorageError`. Or your error
/// context may also be passed with the client, add your error details in
/// `CurpError`, see `Redirect` below.
///
/// Please add comments above your error if you want to extend more :)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurpError {
    #[prost(
        oneof = "curp_error::Err",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14"
    )]
    pub err: ::core::option::Option<curp_error::Err>,
}
/// Nested message and enum types in `CurpError`.
pub mod curp_error {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Redirect {
        #[prost(message, optional, tag = "1")]
        pub leader_id: ::core::option::Option<super::OptionalU64>,
        #[prost(uint64, tag = "2")]
        pub term: u64,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Err {
        /// When a command conflicts with the server SP.
        #[prost(message, tag = "1")]
        KeyConflict(()),
        /// When a proposal id is duplicated.
        #[prost(message, tag = "2")]
        Duplicated(()),
        /// When the client id in a proposal id is expired.
        #[prost(message, tag = "3")]
        ExpiredClientId(()),
        /// When the conf change config is invalid.
        #[prost(message, tag = "4")]
        InvalidConfig(()),
        /// When the conf change proposal remove a node which is not exists.
        #[prost(message, tag = "5")]
        NodeNotExists(()),
        /// When the conf change proposal add a node which is exists.
        #[prost(message, tag = "6")]
        NodeAlreadyExists(()),
        /// When the conf change proposal promote a lazy learner.
        #[prost(message, tag = "7")]
        LearnerNotCatchUp(()),
        /// When the cluster is shutting down
        #[prost(message, tag = "8")]
        ShuttingDown(()),
        /// When the request cluster_version does not match the cluster's.
        #[prost(message, tag = "9")]
        WrongClusterVersion(()),
        /// When rpc transport error happens, this means the request does not
        /// send to server
        #[prost(message, tag = "10")]
        RpcTransport(()),
        /// When the request should be send to leader and this node is not the
        /// leader. Return the context to client to update its state.
        #[prost(message, tag = "11")]
        Redirect(Redirect),
        /// The internal error that the client never concerned.
        /// e.g.
        /// 1. failed to allocate a new snapshot
        /// 2. failed to reset the command executor by snapshot
        /// 3. failed to get last applied index from command executor.
        /// 4. io::Error
        /// 5. failed to encode and decode some stuff, like pb serialize or
        ///    bincode serialize.
        /// 6. failed in storage layer
        ///    ...
        #[prost(string, tag = "12")]
        Internal(::prost::alloc::string::String),
        /// When the leader is transferring or an error occurred in the transfer
        #[prost(string, tag = "13")]
        LeaderTransfer(::prost::alloc::string::String),
        /// When the leader is a zombie
        #[prost(message, tag = "14")]
        Zombie(()),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeRequest {
    #[prost(message, optional, tag = "1")]
    pub propose_id: ::core::option::Option<ProposeId>,
    /// The serialized command
    /// The original type is `Command`
    #[prost(bytes = "vec", tag = "2")]
    pub command: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub cluster_version: u64,
    #[prost(uint64, tag = "4")]
    pub term: u64,
    #[prost(bool, tag = "5")]
    pub slow_path: bool,
    #[prost(uint64, tag = "6")]
    pub first_incomplete: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<CmdResult>,
    #[prost(bool, tag = "2")]
    pub conflict: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncedResponse {
    /// The serialized command after sync result
    /// The original type is Result<Command::ASR, Command::Error>
    #[prost(message, optional, tag = "1")]
    pub after_sync_result: ::core::option::Option<CmdResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpResponse {
    #[prost(oneof = "op_response::Op", tags = "1, 2")]
    pub op: ::core::option::Option<op_response::Op>,
}
/// Nested message and enum types in `OpResponse`.
pub mod op_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Op {
        #[prost(message, tag = "1")]
        Propose(super::ProposeResponse),
        #[prost(message, tag = "2")]
        Synced(super::SyncedResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordRequest {
    #[prost(message, optional, tag = "1")]
    pub propose_id: ::core::option::Option<ProposeId>,
    /// The serialized command
    /// The original type is `Command`
    #[prost(bytes = "vec", tag = "2")]
    pub command: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RecordResponse {
    #[prost(bool, tag = "1")]
    pub conflict: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WaitSyncedRequest {
    #[prost(message, optional, tag = "1")]
    pub propose_id: ::core::option::Option<ProposeId>,
    #[prost(uint64, tag = "2")]
    pub cluster_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WaitSyncedResponse {
    /// The serialized command after sync result
    /// The original type is Result<Command::ASR, Command::Error>
    #[prost(message, optional, tag = "1")]
    pub after_sync_result: ::core::option::Option<CmdResult>,
    /// The serialized command execute result
    /// The original type is Result<Command::ER, Command::Error>
    #[prost(message, optional, tag = "2")]
    pub exe_result: ::core::option::Option<CmdResult>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FetchClusterRequest {
    #[prost(bool, tag = "1")]
    pub linearizable: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchClusterResponse {
    #[prost(message, optional, tag = "1")]
    pub leader_id: ::core::option::Option<OptionalU64>,
    #[prost(uint64, tag = "2")]
    pub term: u64,
    #[prost(uint64, tag = "3")]
    pub cluster_id: u64,
    #[prost(message, repeated, tag = "4")]
    pub members: ::prost::alloc::vec::Vec<Member>,
    #[prost(uint64, tag = "5")]
    pub cluster_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchReadStateRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub command: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub cluster_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchReadStateResponse {
    #[prost(oneof = "fetch_read_state_response::ReadState", tags = "1, 2")]
    pub read_state: ::core::option::Option<fetch_read_state_response::ReadState>,
}
/// Nested message and enum types in `FetchReadStateResponse`.
pub mod fetch_read_state_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct IdSet {
        #[prost(uint64, repeated, tag = "1")]
        pub inflight_ids: ::prost::alloc::vec::Vec<u64>,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ReadState {
        #[prost(message, tag = "1")]
        Ids(IdSet),
        #[prost(uint64, tag = "2")]
        CommitIndex(u64),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShutdownRequest {
    #[prost(message, optional, tag = "1")]
    pub propose_id: ::core::option::Option<ProposeId>,
    #[prost(uint64, tag = "2")]
    pub cluster_version: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShutdownResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeConfChangeRequest {
    #[prost(message, optional, tag = "1")]
    pub propose_id: ::core::option::Option<ProposeId>,
    #[prost(message, repeated, tag = "2")]
    pub changes: ::prost::alloc::vec::Vec<propose_conf_change_request::ConfChange>,
    #[prost(uint64, tag = "3")]
    pub cluster_version: u64,
}
/// Nested message and enum types in `ProposeConfChangeRequest`.
pub mod propose_conf_change_request {
    #[derive(serde::Deserialize, serde::Serialize, Clone, PartialEq, ::prost::Message)]
    pub struct ConfChange {
        #[prost(enumeration = "ConfChangeType", tag = "1")]
        pub change_type: i32,
        #[prost(uint64, tag = "2")]
        pub node_id: u64,
        #[prost(string, repeated, tag = "3")]
        pub address: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum ConfChangeType {
        Add = 0,
        AddLearner = 1,
        Remove = 2,
        Update = 3,
        Promote = 4,
    }
    impl ConfChangeType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Add => "Add",
                Self::AddLearner => "AddLearner",
                Self::Remove => "Remove",
                Self::Update => "Update",
                Self::Promote => "Promote",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Add" => Some(Self::Add),
                "AddLearner" => Some(Self::AddLearner),
                "Remove" => Some(Self::Remove),
                "Update" => Some(Self::Update),
                "Promote" => Some(Self::Promote),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeConfChangeResponse {
    #[prost(message, repeated, tag = "1")]
    pub members: ::prost::alloc::vec::Vec<Member>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishRequest {
    #[prost(message, optional, tag = "1")]
    pub propose_id: ::core::option::Option<ProposeId>,
    #[prost(uint64, tag = "2")]
    pub node_id: u64,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub client_urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PublishResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MoveLeaderRequest {
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    #[prost(uint64, tag = "2")]
    pub cluster_version: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MoveLeaderResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaseKeepAliveMsg {
    #[prost(uint64, tag = "1")]
    pub client_id: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReadIndexRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReadIndexResponse {
    #[prost(uint64, tag = "1")]
    pub term: u64,
}
