// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendEntriesRequest {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(uint64, tag = "2")]
    pub leader_id: u64,
    #[prost(uint64, tag = "3")]
    pub prev_log_index: u64,
    #[prost(uint64, tag = "4")]
    pub prev_log_term: u64,
    #[prost(bytes = "vec", repeated, tag = "5")]
    pub entries: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag = "6")]
    pub leader_commit: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AppendEntriesResponse {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(uint64, tag = "3")]
    pub hint_index: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VoteRequest {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(uint64, tag = "2")]
    pub candidate_id: u64,
    #[prost(uint64, tag = "3")]
    pub last_log_index: u64,
    #[prost(uint64, tag = "4")]
    pub last_log_term: u64,
    #[prost(bool, tag = "5")]
    pub is_pre_vote: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoteResponse {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(bool, tag = "2")]
    pub vote_granted: bool,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub spec_pool: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, tag = "4")]
    pub shutdown_candidate: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstallSnapshotRequest {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(uint64, tag = "2")]
    pub leader_id: u64,
    #[prost(uint64, tag = "3")]
    pub last_included_index: u64,
    #[prost(uint64, tag = "4")]
    pub last_included_term: u64,
    #[prost(uint64, tag = "5")]
    pub offset: u64,
    #[prost(bytes = "bytes", tag = "6")]
    pub data: ::prost::bytes::Bytes,
    #[prost(bool, tag = "7")]
    pub done: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InstallSnapshotResponse {
    #[prost(uint64, tag = "1")]
    pub term: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TriggerShutdownRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TriggerShutdownResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TryBecomeLeaderNowRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TryBecomeLeaderNowResponse {}
