# @generated by `cargo buckal`

load("@prelude//cfg/modifier:cfg_constructor.bzl", "cfg_constructor_post_constraint_analysis", "cfg_constructor_pre_constraint_analysis")
load("@prelude//cfg/modifier:common.bzl", "MODIFIER_METADATA_KEY")

def set_cfg_constructor(aliases = dict()):
    project_root_cell = read_root_config("cell_aliases", "root")
    current_root_cell = read_config("cell_aliases", "root")
    if project_root_cell == current_root_cell:
        native.set_cfg_constructor(
            stage0 = cfg_constructor_pre_constraint_analysis,
            stage1 = cfg_constructor_post_constraint_analysis,
            key = MODIFIER_METADATA_KEY,
            aliases = struct(**aliases),
            extra_data = struct(),
        )