on:
  pull_request:
    paths:
      - 'project/**'
      - 'third-party/**'
      - 'platforms/**'
      - 'toolchains/**'
      - '.buckconfig'
      - '.github/workflows/base.yml'

name: Check, Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Rustfmt Check
    runs-on: rk8s-runner-set
    steps:
      - uses: actions/checkout@v6
      - run: |
          cd project
          cargo fmt --all --check

  clippy:
    name: Clippy Check
    strategy:
      fail-fast: true
    runs-on: rk8s-runner-set
    steps:
      - uses: actions/checkout@v6
      - run: |
          cd project
          cargo clippy --workspace -- -D warnings

  redundancy:
    name: Redundancy Check
    runs-on: rk8s-runner-set
    steps:
      - uses: actions/checkout@v6
      - run: |
          x=$(find third-party/rust/crates -mindepth 2 -maxdepth 2 -type d -exec bash -c '
            n=$(find "$1" -maxdepth 1 -type f | wc -l)
            [ $n -gt 1 ]
          ' _ {} \; -print -quit | wc -l)
          if [ $x -gt 0 ]; then
            echo "❌ Redundant directories found"
            exit 1
          else
            echo "✅ All good"
            exit 0
          fi

  build:
    name: Buck2 Build
    runs-on: rk8s-runner-set
    steps:
      - uses: actions/checkout@v6
      - run: buck2 build //project/...

  test:
    name: Buck2 Test
    runs-on: rk8s-runner-set
    steps:
      - uses: actions/checkout@v6
      - run: |
          echo "buck2 test"
